# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'OpAdxSdkDemo_OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpAdxSdk',  '2.14.0'

end
